services:
  base_legada:
    image: base-legada:1.0
    container_name: base-legada
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    env_file: .env
    restart: always
    deploy:
      resources:
        limits:
          memory: 2048M
    ports:
      - "${HOST_DB_PORT}:3306"
    volumes:
      - base-legada-data:/var/lib/mysql

volumes:
  base-legada-data: