services:

  base_legada_test:
    image: base-legada-test:1.0
    container_name: base-legada-test
    build:
      context: .
      dockerfile: ./docker/mysql-test/Dockerfile
    env_file: .env
    restart: always
    deploy:
      resources:
        limits:
          memory: 2048M
    ports:
      - "${HOST_DB_TEST_PORT}:3306"