spring:
  application:
    name: avaliacao-tecnica-canais
  config:
    import: optional:classpath:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl : false
    hibernate:
      ddl-auto: none
      format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

api:
    version: /v1

logging:
  level:
    org:
      springframework: DEBUG